### PR TITLE
port code to be python 3 compatible and make mirror and config dir settable from environment

### PR DESCRIPTION
**Pull request by bmanojlovic**
it should work in both python2 and python3 now
if using containers you could get configuration from environment variables

### CODE REVIEW

**Comment by pyther** [comment]
Thanks! I need to spend a few minutes taking a closer look at (I've been swamped), but it looks great at first glance.

**Comment by bmanojlovic** [comment]
i have updated PR with few more changes;
use modifyrepo to add updateinfo into repodata
added simple Dockerfile for future use from docker container
add logic that will use all cpu cores in createrepo - speeding up regeneration of metadata

**Comment by viniciusferrao** [comment]
Now with RHEL8 in the wild this patch is a must.

**Comment by steftux** [comment]
I have done the same code changes before seeing this pull request. I would appreciate the merge into master.

**Comment by viniciusferrao** [comment]
I think the lead developer has abandoned the code. Not blaming he anyway, but perhaps out of time or lost interest in the project.

**Pull request closed without merging**
